### ISSUE TITLE
INPUT_PULLUP version?

### ISSUE THREAD

**Issue by robmurru** [arthus701/midibigbutton#2]
Hi, I'm trying to make an hybrid version between the "refactored" code and this MIDI version edited with INPUT_PULLUP instead of INPUT, with a mode selection with an added switch connected to the Leonardo. The standard version works good but this midi version does not work at all, when using it with ableton for every clock count it adds a note without even touching the "big button". 
Is this midi version working good (like the standard one, adding the note when pressing the big button) with the external pull down resistor or is it supposed to add a note for every clock rising edge?

**Comment by arthus701** [comment]
Hi, did you solve the issue?

I'm sorry, but I did not really understand your problem. Did you use the pattern in [this line](https://github.com/arthus701/midibigbutton/blob/master/MIDI_BIG_BUTTON.ino#L58)? Because this one contains a beat on startup, for testing purposes. If you want a clean pattern on startup, you should use the [NullPattern](https://github.com/arthus701/midibigbutton/blob/master/MIDI_BIG_BUTTON.ino#L42) or press the clear button...

Cheers,
Arthus

**Comment by robmurru** [comment]
Hi,
Yes sorry, I did not notice the nullpattern at first glance, now I solved the issue! I thought it was giving me problems because the code does not use the input_pullup mode for the inputs (which I used for the original lmnc big button).
By the way thanks 😁
